// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhEg0w0AscJdUn3ST3xVbV1ijNz3Y069E',
    appId: '1:194786654037:web:302036fcd61b06d02461dc',
    messagingSenderId: '194786654037',
    projectId: 'midtermproject-1a9d8',
    authDomain: 'midtermproject-1a9d8.firebaseapp.com',
    storageBucket: 'midtermproject-1a9d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqdTKk6TuliB4IO6THpTI6NuKkezCf7tg',
    appId: '1:194786654037:android:c3144d253a22531c2461dc',
    messagingSenderId: '194786654037',
    projectId: 'midtermproject-1a9d8',
    storageBucket: 'midtermproject-1a9d8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhEg0w0AscJdUn3ST3xVbV1ijNz3Y069E',
    appId: '1:194786654037:web:713b53dc37f5a6832461dc',
    messagingSenderId: '194786654037',
    projectId: 'midtermproject-1a9d8',
    authDomain: 'midtermproject-1a9d8.firebaseapp.com',
    storageBucket: 'midtermproject-1a9d8.firebasestorage.app',
  );
}
